[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
#nerdtree
repo = 'scrooloose/nerdtree'

[[plugins]]
#nerdtree-tab
repo = 'jistr/vim-nerdtree-tabs'
hook_add = 'let g:nerdtree_tabs_open_on_console_startup=1'

[[plugins]]
#インデント可視化
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_powerline_fonts = 1
set laststatus=2
let g:airline_theme = 'jellybeans'
'''

[[plugins]]
 repo = 'vim-airline/vim-airline-themes'

[[plugins]]
#複数行コメントアウト
  repo = 'tyru/caw.vim.git'
  hook_add = '''
  nmap <C-K> <Plug>(caw:hatpos:toggle)
  vmap <C-K> <Plug>(caw:hatpos:toggle)
  '''

[[plugins]]
#template
	repo = 'mattn/sonictemplate-vim'
	#set template directory
	hook_add = '''
      let g:sonictemplate_vim_template_dir = [
      \ '~/.vim/template'
      \]
  '''
[[plugins]]
#自動括弧
repo = 'cohama/lexima.vim'
on_i = 1


