[[plugins]]
 repo = 'roxma/nvim-yarp'

[[plugins]]
 repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
 repo = 'Shougo/deoplete.nvim'
 depends = ['nvim-yarp','vim-hug-neovim-rpc']
 hook_add = 'let g:deoplete#enable_at_startup = 1'
 on_i = 1

[[plugins]]
 repo = 'zchee/deoplete-jedi'
 on_ft = 'python'
 hook_add = 
'''
autocmd FileType python setlocal completeopt-=preview "docstringは表示しない
"let g:deoplete#sources#jedi#statement_length=100
"" jedi本体の補完は切る（deoplete-jediで非同期処理をしてくれるため）
"let g:jedi#completions_enabled = 0
'''
 depends = ['deoplete.nvim']


[[plugins]]
#自動括弧
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
#pep8インデント
repo = 'Vimjas/vim-python-pep8-indent'
on_i = 1

