[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['nvim-yarp','vim-hug-neovim-rpc']
hook_add = 'let g:deoplete#enable_at_startup = 1'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
hook_add = 
'''
autocmd FileType python setlocal completeopt-=preview "docstringは表示しない
'''
depends = ['deoplete.nvim']

[[plugins]]
# Quickrun \rで実行 \qで閉じる
#set splitright
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {}
let g:quickrun_config._ = {
      \ 'outputter' : 'error',
      \ 'hook/close_quickfix/enable_success' : 1,
      \ 'hook/close_quickfix/enable_exit' : 1,
      \ 'outputter/error/success' : 'buffer',
      \ 'outputter/error/error'   : 'quickfix',
      \ 'outputter/buffer/split'  : ':rightbelow 8sp',
      \ 'outputter/buffer/close_on_empty' : 1,
      \ }
let g:quickrun_config.cpp = { 'command': 'g++', 'cmdopt': '-std=c++11' }
let g:quickrun_config.markdown = { 'outputter': 'browser' }
nnoremap <Leader>q :<C-u>bw! \[quickrun\ output\]<CR>
au FileType qf nnoremap <silent><buffer>q :quit<CR>
'''
on_i = 1


[[plugins]]
#pep8インデント
repo = 'Vimjas/vim-python-pep8-indent'
on_i = 1

